# TypeProf 0.31.1

# lib/nob/templates/operators/time.rb
module Nob
  module Nob::Templates
    module Nob::Templates::Operators
      class Nob::Templates::Operators::Time # failed to identify its superclass
        def call: (title: untyped, now: untyped) -> untyped
      end
    end
  end
end
