# TypeProf 0.31.1

# lib/nob/templates/operators/title.rb
module Nob
  module Nob::Templates
    module Nob::Templates::Operators
      class Nob::Templates::Operators::Title # failed to identify its superclass
        def initialize: (untyped) -> void
        def call: (title: untyped, now: untyped) -> untyped
      end
    end
  end
end
