# TypeProf 0.31.1

# lib/nob/notes/daily.rb
module Nob
  module Nob::Notes
    class Nob::Notes::Daily
      Nob::Notes::Daily::Result: untyped
      def self.create: (vault: untyped, base_path: untyped, file_name_format: untyped, ?template_text: nil, ?now: Time, ?force: false) -> untyped
      def self.render: (template_text: nil, title: String, now: Time) -> String
    end
  end
end
