# TypeProf 0.31.1

# lib/nob/notes/lister.rb
module Nob
  module Nob::Notes
    class Nob::Notes::Lister
      class Nob::Notes::Lister::InvalidPrefix # failed to identify its superclass
      end
      class Nob::Notes::Lister::PrefixNotFound # failed to identify its superclass
      end
      def self.list: (vault: untyped, ?prefix: nil) -> untyped
      def self.normalize_prefix: (nil, vault: untyped) -> nil
      def self.validate_base!: (String, nil) -> nil
    end
  end
end
