# TypeProf 0.31.1

# lib/nob/notes/viewer.rb
module Nob
  module Nob::Notes
    class Nob::Notes::Viewer
      class Nob::Notes::Viewer::NotFound # failed to identify its superclass
      end
      class Nob::Notes::Viewer::Ambiguous # failed to identify its superclass
      end
      class Nob::Notes::Viewer::InvalidFrontmatter # failed to identify its superclass
      end
      Nob::Notes::Viewer::YAML_LOADER: untyped
      def self.show: (vault: untyped, title: untyped) -> untyped
    end
  end
end
